### ISSUE TITLE
libImageOperationLib.so cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CodeLiSW** [MrPeterJin/kfb-reader#1]
Thanks for your work on this kfb package.
I followed your instructions, and when I did this：
from kfb import KfbSlide
slide = KfbSlide('my.kfb')
Error comes out with "libImageOperationLib.so cannot open shared object file: No such file or directory".

I've already installed openslide-python in my conda envs with these commands below:
sudo apt-get install openslide-tools
sudo apt-get install python-openslide
pip install openslide-python

Do you have any ideas on solving this?
Thanks in advance!

**Comment by MrPeterJin** [comment]
Hi, sorry for the late reply, you can see the new README file to see if it is working normally.

**Comment by MrPeterJin** [comment]
Closed due to inactivity.
