### ISSUE TITLE
format

### ISSUE THREAD

**Issue by lingxitong** [MrPeterJin/kfb-reader#2]
Can I understand the package in this way: I can use it load most formats of wsi

**Comment by MrPeterJin** [comment]
Yes, of course

**Comment by lingxitong** [comment]
can I use openslide API to cut_patches in sdpc-format wsi?

**Comment by MrPeterJin** [comment]
Yes, you can call `read_region` to do so.
*Do make sure you have sudo privilege of your device

**Comment by lingxitong** [comment]
thanks

**Comment by MrPeterJin** [comment]
Closed as completed.
