### ISSUE TITLE
convert 

### ISSUE THREAD

**Issue by lingxitong** [MrPeterJin/kfb-reader#3]
hello,this package realize the reading for many formats of WSI by python,so can your package realize the convert from one format to another,thanks

**Comment by MrPeterJin** [comment]
Hi, I don't have much knowledge in that, maybe you can try to implement that or recommend someone who has the ability to implement that. Thanks!

**Comment by lingxitong** [comment]
OK,once I made it,I will pull requests.

**Comment by MrPeterJin** [comment]
Thanks!

**Comment by MrPeterJin** [comment]
Closed due to inactivity. @lingxitong You can reopen once you are ready for a PR.
