### ISSUE TITLE
memory leak about Slide obj and tile obj for kfb file

### ISSUE THREAD

**Issue by VincentXu521** [MrPeterJin/kfb-reader#4]
For .kfb file：
``` python
def func(***):
            slide = Slide(kfbpath)
            data_gen = KfbDZG(slide, tile_size=TileSize-2, overlap=1)
            img = data_gen.get_tile(level, (PositionX, PositionY))
            imgByteArr = io.BytesIO()
            img.save(imgByteArr, format='JPEG')
            imgByteArr_value = imgByteArr.getvalue()
            img.close()
            slide.close()
            return imgByteArr_value 
```
slide.close and img.close do NOT work?
Memory will continue to grow with multiple function calls.

**Comment by MrPeterJin** [comment]
Sorry, this is probably due to there is no close() function implemented in kfb related lines. You can try to fix by adding close method in kfb related lines by yourself. PR to this repo will be more than appreciated. Currently I am busy and do not have much energy to handle this problem.

**Comment by VincentXu521** [comment]
Thank you very much for your reply, these days I'm locating the problem and looking for alternatives. I think your code is well written, the memory leak should be caused by the libkfbslide.so shared object library, whose slide close method and the method to generate the tile failed to release the resources. However I can't find any C/C++ repository that compiles this shared object library. Thanks again for the code contribution.
